version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - docker build -t tarentum-wiki:latest -f Dockerfile .
      - docker tag tarentum-wiki:latest 726009275047.dkr.ecr.us-west-2.amazonaws.com/tarentum-wiki:latest

  post_build:
    commands:
      - docker push 726009275047.dkr.ecr.us-west-2.amazonaws.com/tarentum-wiki:latest
